//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIC_AMZ_API
{
    using System;
    
    public partial class AmazonFeed
    {
        public string feed_product_type { get; set; }
        public string item_sku { get; set; }
        public string brand_name { get; set; }
        public string external_product_id { get; set; }
        public string external_product_id_type { get; set; }
        public string item_name { get; set; }
        public string manufacturer { get; set; }
        public string recommended_browse_nodes { get; set; }
        public Nullable<decimal> standard_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string main_image_url { get; set; }
    }
}
