//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIC_AMZ_API
{
    using System;
    
    public partial class AmazonFeedPrice
    {
        public string item_sku { get; set; }
        public Nullable<decimal> standard_price { get; set; }
    }
}
