//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIC_AMZ_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MICShoppingEntities : DbContext
    {
        public MICShoppingEntities()
            : base("name=MICShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AmazonFeed> GetAmazonFeed()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AmazonFeed>("GetAmazonFeed");
        }
    
        public virtual ObjectResult<AmazonFeedPrice> GetAmazonFeedPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AmazonFeedPrice>("GetAmazonFeedPrice");
        }
    
        public virtual ObjectResult<AmazonFeedQty> GetAmazonFeedQty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AmazonFeedQty>("GetAmazonFeedQty");
        }
    }
}
